/*<TOAD_FILE_CHUNK>*/
--create table MIGADM.EIT_MOCK as select * from tbaadm.eit
--drop table MIGADM.EIT_MOCK
--se
--select distinct INTEREST_CALC_UPTO_DATE_DR from custom.int_upl

declare
    cursor c1 is
    
    select E.FORACID,GAM.ACID, E.CRNCY_CODE,E.SOL_ID,INTEREST_CALC_UPTO_DATE_CR,ACCRUED_UPTO_DATE_CR,BOOKED_UPTO_DATE_CR,
XFER_INT_AMT_CR,NRML_ACCRUED_AMOUNT_CR,NRML_BOOKED_AMOUNT_CR,INTEREST_CALC_UPTO_DATE_DR,ACCRUED_UPTO_DATE_DR,
BOOKED_UPTO_DATE_DR,XFER_INT_AMT_DR,NRML_ACCRUED_AMOUNT_DR,NRML_BOOKED_AMOUNT_DR,
'' LAST_NRML_BOOKED_AMOUNT_DR,PENALINT_ACCRUED_AMOUNT_DR,PENALINT_BOOKED_AMOUNT_DR,PENAL_INTEREST_AMOUNT_DR  from custom.int_upl E,
TBAADM.GAM WHERE GAM.FORACID = E.FORACID ;

begin
    for i in  c1
loop

    UPDATE TBAADM.EIT e SET
    e.INTEREST_CALC_UPTO_DATE_DR = to_char(i.INTEREST_CALC_UPTO_DATE_DR,'dd-mm-yyyy'),
    e.ACCRUED_UPTO_DATE_DR = to_char(i.ACCRUED_UPTO_DATE_DR,'dd-mm-yyyy'),
    e.BOOKED_UPTO_DATE_DR = to_char(i.BOOKED_UPTO_DATE_DR,'dd-mm-yyyy'),
    e.NRML_ACCRUED_AMOUNT_DR = i.NRML_ACCRUED_AMOUNT_DR,
    e.NRML_BOOKED_AMOUNT_DR = i.NRML_BOOKED_AMOUNT_DR,
    e.LAST_NRML_BOOKED_AMOUNT_DR = i.LAST_NRML_BOOKED_AMOUNT_DR
    WHERE e.ENTITY_ID = i.ACID; 
    commit;
end loop;

END;

/*<TOAD_FILE_CHUNK>*/
COMMIT;


